services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: kr1ston
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}