# docker-compose.dev.yml  
version: '0.1'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=bloguser
      - MYSQL_PASSWORD=blogpass
      - MYSQL_DATABASE=blogdb
    depends_on:
      db:
        condition: service_healthy
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=blogdb
      - MYSQL_USER=bloguser
      - MYSQL_PASSWORD=blogpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
